# ZSH Config
# Josh Kaplan

export ZSH=$HOME/.oh-my-zsh
export PGDATA="/usr/local/var/postgres" # Postgres
export SSH_KEY_PATH="~/.ssh/dsa_id" # SSH
# PATH
export PATH="/usr/local/bin:/usr/local/sbin:~/bin:$PATH" # Homebrew
# Editors
export EDITOR=vim
export VISUAL=vim

ZSH_THEME="agnoster"
DEFAULT_USER="josh"
ENABLE_CORRECTION="true" # Auto Correct

# LIBRARIES 
##############################

# oh-my-zsh
plugins=(git sublime osx)
source $ZSH/oh-my-zsh.sh

# Shell integration
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# rbenv (ruby)
eval "$(rbenv init -)"

# Github
eval "$(hub alias -s)"


# SETTINGS
##############################

# Vim Keybindings
bindkey -v

# Separate Histories
unsetopt inc_append_history
unsetopt share_history

# Online Help
# unalias run-help
autoload run-help
HELPDIR=/usr/local/share/zsh/help

# Auto Completion
zmodload zsh/complist
bindkey -M menuselect ' ' accept-and-infer-next-history
bindkey -M menuselect '^?' undo

# SOURCE MORE STUFF
##############################

# Aliases (sourced near the end so they override other defaults)
source ./aliases.zsh

# Local overrides
if [ -e ~/.local.zsh ]; then
    source ~/.local.zsh
fi
